name: Publish Changelog

on:
  workflow_dispatch:
  schedule:
  - cron: '0 10 * * *'

jobs:
  publish_changelog:
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v3
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        ref: master

    - name: Publish changelog
      run: Tools/actions_changelogs_since_last_run.py
      env:
        CHANGELOG_DIR: ${{ vars.CHANGELOG_DIR }}
        CHANGELOG_WEBHOOK: ${{ secrets.CHANGELOG_WEBHOOK }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
