name: YAML Linter Secrets

on:
  push:
    branches: [ master, staging, stable ]
  merge_group:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]

jobs:
  build:
    name: YAML Linter Secrets
    if: ${{ vars.SECRETSLINK != '' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.6.0
    - name: Setup submodule
      run: |
        git submodule update --init --recursive
    - name: Download parts
      run: |
        git clone ${{ secrets.SECRETSFRONTIER }}
        mv SecretsFrontier/_PrivateResources/_SPrototypes Resources/Prototypes/
        mv SecretsFrontier/_PrivateResources/_STextures Resources/Textures/
        mv SecretsFrontier/_PrivateShared Content.Shared/_PrivateShared
        mv SecretsFrontier/_PrivateServer Content.Server/_PrivateServer
        mv SecretsFrontier/_PrivateClient Content.Client/_PrivateClient
    - name: Pull engine updates
      uses: space-wizards/submodule-dependency@v0.1.5
    - name: Update Engine Submodules
      run: |
        cd RobustToolbox/
        git submodule update --init --recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: 9.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore /p:WarningsAsErrors= /m
    - name: Run Linter
      run: dotnet run --project Content.YAMLLinter/Content.YAMLLinter.csproj --no-build
